// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALuaONpwicGKCqGeUhEzuhcRFdHzKXoyg',
    appId: '1:360797608173:web:71fa5a4fc6b9927b5414e4',
    messagingSenderId: '360797608173',
    projectId: 'bookstroe-88651',
    authDomain: 'bookstroe-88651.firebaseapp.com',
    storageBucket: 'bookstroe-88651.appspot.com',
    measurementId: 'G-T6E2VTSCGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNIPkE7r70-pnRJAyq5vpUpQTN7fT98PE',
    appId: '1:360797608173:android:3566e654680ec6305414e4',
    messagingSenderId: '360797608173',
    projectId: 'bookstroe-88651',
    storageBucket: 'bookstroe-88651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWFbRMaoBmeMl-DAozdQyMHD5JP5y1R4',
    appId: '1:360797608173:ios:f6790aa3119957265414e4',
    messagingSenderId: '360797608173',
    projectId: 'bookstroe-88651',
    storageBucket: 'bookstroe-88651.appspot.com',
    iosClientId: '360797608173-ae06od017j546garkfqhmuh5jf3aj1kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUWFbRMaoBmeMl-DAozdQyMHD5JP5y1R4',
    appId: '1:360797608173:ios:f6790aa3119957265414e4',
    messagingSenderId: '360797608173',
    projectId: 'bookstroe-88651',
    storageBucket: 'bookstroe-88651.appspot.com',
    iosClientId: '360797608173-ae06od017j546garkfqhmuh5jf3aj1kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStore',
  );
}
